/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Programdata;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author HP
 */
public class Edit_dbpasien extends javax.swing.JFrame {
        String user="root";
        String pswd ="";
        String host="localhost";
        String db="dblogin";
        String url="";
        private Connection Lconnection=null;
        private JTable table=null;
    
    /**
     * Creates new form RegisPasien
     */
    public Edit_dbpasien() throws SQLException{
        initComponents();  
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user+ "&password="+ pswd;
            Lconnection=DriverManager.getConnection(url);
        }
        catch(ClassNotFoundException e) {
            System.out.println("Driver tidak ditemukan");
        }
        catch (SQLException e){
            System.out.println("koneksi gagal:" +
            e.toString());
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtnamaP1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtnamaP2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel1 = new javax.swing.JPanel();
        txtusiaP = new javax.swing.JTextField();
        txtalamatP = new javax.swing.JTextField();
        txtnamaP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnbatal = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtteleponP = new javax.swing.JTextField();
        tbmainmenu = new javax.swing.JButton();
        txtidP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btncekidP = new javax.swing.JButton();
        btnceknama = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setText("NAMA PASIEN");

        jLabel8.setText("NAMA PASIEN");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/asset/icon.png")).getImage());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        txtalamatP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalamatPActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("USIA");

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("NAMA PASIEN");

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("ALAMAT");

        btnbatal.setText("RESET");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        btnsimpan.setText("UPDATE");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("NO TELEPON");

        txtteleponP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtteleponPActionPerformed(evt);
            }
        });

        tbmainmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/arrow-small-left.png"))); // NOI18N
        tbmainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbmainmenuActionPerformed(evt);
            }
        });

        txtidP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidPActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("ID PASIEN");

        btncekidP.setText("cek ID");
        btncekidP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncekidPActionPerformed(evt);
            }
        });

        btnceknama.setText("cek nama");
        btnceknama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnceknamaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("UPDATE DATA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtteleponP, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtusiaP, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtalamatP, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnbatal)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnsimpan)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnhapus)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tbmainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1)
                                    .addComponent(txtnamaP, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                                    .addComponent(txtidP))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnceknama)
                                    .addComponent(btncekidP, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(36, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(356, 356, 356))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncekidP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnamaP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnceknama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtteleponP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtusiaP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtalamatP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbatal)
                    .addComponent(btnsimpan)
                    .addComponent(btnhapus)
                    .addComponent(tbmainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        txtnamaP.setText("");
        txtusiaP.setText("");
        txtteleponP.setText("");
        txtalamatP.setText("");
        txtidP.setText("");
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here: 
        try {
            PreparedStatement pStatement =
            Lconnection.prepareStatement("UPDATE tbpasien SET nama=?,umur=?,alamat=?,No_Telepon=? WHERE id=?");
            pStatement.setString(1, txtnamaP.getText());
            pStatement.setString(2, txtusiaP.getText());
            pStatement.setString(3, txtalamatP.getText());
            pStatement.setString(4, txtteleponP.getText());
            pStatement.setString(5, txtidP.getText());

            if (pStatement.executeUpdate()>0)
                JOptionPane.showMessageDialog(this,
                "Edit sukses", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog(this,"Edit gagal", "Informasi",JOptionPane.INFORMATION_MESSAGE);

            pStatement.close();
            
            txtnamaP.setText("");
            txtusiaP.setText("");
            txtteleponP.setText("");
            txtalamatP.setText("");
            txtidP.setText("");
        }
        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void txtteleponPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtteleponPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteleponPActionPerformed

    private void tbmainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbmainmenuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_tbmainmenuActionPerformed

    private void txtidPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidPActionPerformed

    }//GEN-LAST:event_txtidPActionPerformed

    private void btncekidPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncekidPActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        try { 
            Statement st = Lconnection.createStatement();
            ResultSet rs = st.executeQuery
            ("Select * from tbpasien" + " where id='" + txtidP.getText() +"'");
            if (rs.next()) {
                btnsimpan.setEnabled(true);
                txtnamaP.setText(rs.getString("nama"));
                txtusiaP.setText(rs.getString("umur"));
                txtteleponP.setText(rs.getString("No_Telepon"));
                txtalamatP.setText(rs.getString("alamat"));
                txtidP.setText(rs.getString("id"));
            } else {
                JOptionPane.showMessageDialog(this,"ID: Salah",
                "Informasi", JOptionPane.INFORMATION_MESSAGE);
            
            btnsimpan.setEnabled(false);
            txtnamaP.setText("");
            txtusiaP.setText("");
            txtteleponP.setText("");
            txtalamatP.setText("");
            txtnamaP.requestFocus();
            }
        }
        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_btncekidPActionPerformed

    private void btnceknamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnceknamaActionPerformed
        // TODO add your handling code here:
        try {
            Statement st = Lconnection.createStatement();
            ResultSet rs = st.executeQuery("Select * from tbpasien" + " where nama like('%" +txtnamaP.getText() + "%')");
            if (rs.next()) {
                btnsimpan.setEnabled(true);
                txtnamaP.setText(rs.getString("nama"));
                txtusiaP.setText(rs.getString("umur"));
                txtteleponP.setText(rs.getString("No_Telepon"));
                txtalamatP.setText(rs.getString("alamat"));
                txtidP.setText(rs.getString("id"));
            } else {
                JOptionPane.showMessageDialog(this,"Nama:Salah", "Informasi",JOptionPane.INFORMATION_MESSAGE);
                btnsimpan.setEnabled(false);
                txtnamaP.setText("");
                txtusiaP.setText("");
                txtteleponP.setText("");
                txtalamatP.setText("");
                txtidP.requestFocus();
            }
        }
        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_btnceknamaActionPerformed

    private void txtalamatPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalamatPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalamatPActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here: 
        try {
            PreparedStatement pStatement = 
           Lconnection.prepareStatement
            ("DELETE FROM tbpasien WHERE id=?");
            pStatement.setString(1, txtidP.getText());
            if (pStatement.executeUpdate()>0)
                JOptionPane.showMessageDialog
                (this,"Delete sukses", "Informasi", 
               JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog
                (this, "Delete gagal", "Informasi", 
               JOptionPane.INFORMATION_MESSAGE);
                pStatement.close();
            
                txtnamaP.setText("");
                txtusiaP.setText("");
                txtteleponP.setText("");
                txtalamatP.setText("");
                txtnamaP.requestFocus();
        }
        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_dbpasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_dbpasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_dbpasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_dbpasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            try {
                 new Edit_dbpasien().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(Edit_dbpasien.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btncekidP;
    private javax.swing.JButton btnceknama;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton tbmainmenu;
    private javax.swing.JTextField txtalamatP;
    private javax.swing.JTextField txtidP;
    private javax.swing.JTextField txtnamaP;
    private javax.swing.JTextField txtnamaP1;
    private javax.swing.JTextField txtnamaP2;
    private javax.swing.JTextField txtteleponP;
    private javax.swing.JTextField txtusiaP;
    // End of variables declaration//GEN-END:variables
    
    
}

